version: 0.2

env:
  shell: bash
  variables:
    DEV_DIR: "Infrastructure/Environments/Dev"
    PROD_DIR: "Infrastructure/Environments/Prod"
    # Questa variabile decide cosa fare. Default = plan
    TF_COMMAND: "plan" 

phases:
  install:
    commands:
      - echo "START INSTALLATION PHASE"
      - apt-get update && apt-get install -y unzip curl
      - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip -o /tmp/terraform.zip -d /usr/local/bin
      - terraform -version

  pre_build:
    commands:
      - echo "CHECKING CHANGED FILES"
      - git fetch --depth=2 origin main || true
      - CHANGED=$(git diff --name-only HEAD~1 HEAD || true)
      - echo "$CHANGED"
      - TARGET_ENV=""
      - WORKDIR=""
      
      # Rilevamento DEV
      - 'if echo "$CHANGED" | grep -q "^${DEV_DIR}/"; then TARGET_ENV="dev"; WORKDIR="$DEV_DIR"; fi'
      # Rilevamento PROD
      - 'if echo "$CHANGED" | grep -q "^${PROD_DIR}/"; then if [ -n "$TARGET_ENV" ]; then echo "CONFLICT ERROR"; exit 1; fi; TARGET_ENV="prod"; WORKDIR="$PROD_DIR"; fi'
      # Fallback a DEV
      - 'if [ -z "$TARGET_ENV" ]; then echo "USING DEV DEFAULT"; TARGET_ENV="dev"; WORKDIR="$DEV_DIR"; fi'
      
      - cd "$WORKDIR"
      - terraform init -input=false
      - terraform validate

  build:
    commands:
      - echo "EXECUTING TERRAFORM COMMAND: $TF_COMMAND"
      
      # SE E' PLAN: Crea il piano
      - 'if [ "$TF_COMMAND" = "plan" ]; then terraform plan -input=false -out=tfplan; fi'
      
      # SE E' APPLY: Applica il piano esistente
      - 'if [ "$TF_COMMAND" = "apply" ]; then terraform apply -input=false -auto-approve tfplan; fi'

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes