version: 0.2

env:
  shell: bash
  variables:
    DEV_DIR: "Infrastructure/Environments/Dev"
    PROD_DIR: "Infrastructure/Environments/Prod"

phases:
  install:
    commands:
      # Rimosso i due punti dal testo
      - echo "START INSTALLATION PHASE"
      # Semplificata installazione: niente if complessi, niente variabili con due punti
      - yum install -y unzip
      - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip -o /tmp/terraform.zip -d /usr/local/bin
      - terraform -version

  pre_build:
    commands:
      - echo "CHECKING CHANGED FILES"
      - git fetch --depth=2 origin main || true
      - CHANGED=$(git diff --name-only HEAD~1 HEAD || true)
      - echo "$CHANGED"
      - TARGET_ENV=""
      - WORKDIR=""
      
      # Logica DEV (protetta da apici, niente due punti nei messaggi)
      - 'if echo "$CHANGED" | grep -q "^${DEV_DIR}/"; then TARGET_ENV="dev"; WORKDIR="$DEV_DIR"; fi'
      
      # Logica PROD
      - 'if echo "$CHANGED" | grep -q "^${PROD_DIR}/"; then if [ -n "$TARGET_ENV" ]; then echo "CONFLICT ERROR - STOP"; exit 1; fi; TARGET_ENV="prod"; WORKDIR="$PROD_DIR"; fi'
      
      # Default (fallback)
      - 'if [ -z "$TARGET_ENV" ]; then echo "NO CHANGES DETECTED - USING DEV DEFAULT"; TARGET_ENV="dev"; WORKDIR="$DEV_DIR"; fi'
      
      - echo "Selected Target is $TARGET_ENV"
      - cd "$WORKDIR"
      
      - echo "INIT AND VALIDATE PHASE"
      - terraform init -input=false
      - terraform validate

  build:
    commands:
      - echo "PLANNING PHASE"
      - terraform plan -input=false -out=tfplan

  post_build:
    commands:
      - echo "APPLY PHASE"
      - terraform apply -input=false -auto-approve tfplan

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes
  