version: 0.2

env:
  shell: bash
  variables:
    DEV_DIR: "Infrastructure/Environments/Dev"
    PROD_DIR: "Infrastructure/Environments/Prod"

phases:
  install:
    commands:
      - echo "=== APPLY PHASE Installing Terraform ==="
      - apt-get update && apt-get install -y unzip curl
      - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip -o /tmp/terraform.zip -d /usr/local/bin
      - terraform -version

  pre_build:
    commands:
      - echo "=== Detecting which environment to apply ==="
      - export PROJECT_PATH=$(pwd)
      - echo "Current directory $PROJECT_PATH"
      - echo "Listing directory structure:"
      - find . -type f -name "tfplan" 2>/dev/null || echo "No tfplan files found yet"
      - ls -la || true
      # Blocco 1: Verifica directory
      - |
        if [ -d "$DEV_DIR" ]; then
          echo "✓ Dev directory exists"
          ls -la "$DEV_DIR/" || true
        else
          echo "⚠ Dev directory not found at $DEV_DIR"
        fi
      - |
        if [ -d "$PROD_DIR" ]; then
          echo "✓ Prod directory exists"
          ls -la "$PROD_DIR/" || true
        else
          echo "⚠ Prod directory not found at $PROD_DIR"
        fi
      
      - export DEV_PLAN_EXISTS=false
      - export PROD_PLAN_EXISTS=false
      
      # Blocco 2: Verifica plan file per Dev
      - |
        if [ -f "$PROJECT_PATH/$DEV_DIR/tfplan" ]; then
          export DEV_PLAN_EXISTS=true
          echo "✓ Found Dev plan file at $PROJECT_PATH/$DEV_DIR/tfplan"
          ls -lh "$PROJECT_PATH/$DEV_DIR/tfplan"
        else
          echo "✗ Dev plan file not found at $PROJECT_PATH/$DEV_DIR/tfplan"
        fi
      
      # Blocco 3: Verifica plan file per Prod
      - |
        if [ -f "$PROJECT_PATH/$PROD_DIR/tfplan" ]; then
          export PROD_PLAN_EXISTS=true
          echo "✓ Found Prod plan file at $PROJECT_PATH/$PROD_DIR/tfplan"
          ls -lh "$PROJECT_PATH/$PROD_DIR/tfplan"
        else
          echo "✗ Prod plan file not found at $PROJECT_PATH/$PROD_DIR/tfplan"
        fi
      
      # Blocco 4: Info se nessun piano trovato
      - |
        if [ "$DEV_PLAN_EXISTS" = "false" ] && [ "$PROD_PLAN_EXISTS" = "false" ]; then
          echo "INFO: No plan file found for Dev or Prod"
          echo "Pipeline will complete successfully without applying changes"
        fi
      
      # Salva le variabili per la fase successiva
      - echo "DEV_PLAN_EXISTS=$DEV_PLAN_EXISTS" > /tmp/env_vars.txt
      - echo "PROD_PLAN_EXISTS=$PROD_PLAN_EXISTS" >> /tmp/env_vars.txt
      - echo "PROJECT_PATH=$PROJECT_PATH" >> /tmp/env_vars.txt

  build:
    commands:
      - echo "=== Executing Terraform Apply ==="
      - source /tmp/env_vars.txt
      - echo "DEV_PLAN_EXISTS $DEV_PLAN_EXISTS"
      - echo "PROD_PLAN_EXISTS $PROD_PLAN_EXISTS"
      
      # Blocco Apply Dev
      - |
        if [ "$DEV_PLAN_EXISTS" = "true" ]; then
          echo "--- Applying terraform changes for DEV ---"
          cd "$PROJECT_PATH/$DEV_DIR" || exit 1
          terraform init -input=false
          terraform apply -input=false -auto-approve tfplan
          echo "✓ Dev apply completed successfully"
        fi
      
      # Blocco Apply Prod
      - |
        if [ "$PROD_PLAN_EXISTS" = "true" ]; then
          echo "--- Applying terraform changes for PROD ---"
          cd "$PROJECT_PATH/$PROD_DIR" || exit 1
          terraform init -input=false
          terraform apply -input=false -auto-approve tfplan
          echo "✓ Prod apply completed successfully"
        fi
      
      # Se nessun piano, esci pulito
      - |
        if [ "$DEV_PLAN_EXISTS" = "false" ] && [ "$PROD_PLAN_EXISTS" = "false" ]; then
          echo "No plan file found. Skipping terraform apply."
          exit 0
        fi

  post_build:
    commands:
      - echo "=== Apply phase completed ==="