version: 0.2

env:
  shell: bash
  variables:
    # ATTENZIONE ALLE MAIUSCOLE/MINUSCOLE QUI SOTTO!
    # Se la tua cartella su git è "dev" (minuscolo), scrivi "dev".
    DEV_DIR: "Infrastructure/Environments/Dev"
    PROD_DIR: "Infrastructure/Environments/Prod"
    TF_COMMAND: "plan"

phases:
  install:
    commands:
      - echo "START INSTALLATION PHASE"
      - apt-get update && apt-get install -y unzip curl
      - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip -o /tmp/terraform.zip -d /usr/local/bin
      - terraform -version

  pre_build:
    commands:
      - echo "DEBUGGING DIRECTORY STRUCTURE"
      # Questo comando ci mostrerà nei log come sono scritte le cartelle (Maiuscole/Minuscole)
      - find . -maxdepth 4 -not -path '*/.*'
      
      - echo "CHECKING CHANGED FILES"
      # FIX: Usiamo 'git show' invece di diff. Guarda solo il commit attuale. Molto più solido.
      - CHANGED=$(git show --name-only --pretty="" HEAD || true)
      
      - echo "Files changed -> $CHANGED"
      
      - TARGET_ENV=""
      - WORKDIR=""
      
      # Logica DEV
      - 'if echo "$CHANGED" | grep -q "^${DEV_DIR}/"; then TARGET_ENV="dev"; WORKDIR="$DEV_DIR"; fi'
      
      # Logica PROD
      - 'if echo "$CHANGED" | grep -q "^${PROD_DIR}/"; then if [ -n "$TARGET_ENV" ]; then echo "CONFLICT ERROR"; exit 1; fi; TARGET_ENV="prod"; WORKDIR="$PROD_DIR"; fi'
      
      # Default
      - 'if [ -z "$TARGET_ENV" ]; then echo "NO SPECIFIC ENV DETECTED - USING DEV"; TARGET_ENV="dev"; WORKDIR="$DEV_DIR"; fi'
      
      - echo "Selected Target is $TARGET_ENV"
      - echo "Entering directory $WORKDIR"
      - cd "$WORKDIR"
      
      - echo "INIT AND VALIDATE"
      - terraform init -input=false
      - terraform validate

  build:
    commands:
      - echo "EXECUTING TERRAFORM ACTION $TF_COMMAND"
      - 'if [ "$TF_COMMAND" = "plan" ]; then terraform plan -input=false -out=tfplan; fi'
      - 'if [ "$TF_COMMAND" = "apply" ]; then terraform apply -input=false -auto-approve tfplan; fi'

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes